### ISSUE TITLE
Implement SOAP API for use by Web layer

### ISSUE THREAD

**Issue by mschvarc** [mschvarc/PB138-Inventory-Management#11]
https://github.com/mschvarc/PB138-Inventory-Management/pull/10 shows preliminary work on the SOAP API implementation

**Comment by dee-gmiterko** [comment]
We should move set-up of testing data somewhere else. Then this part whould be finished.

**Comment by mschvarc** [comment]
You are correct, I've now moved the 'clearDatabase' and 'addTestData' to DebugSoapBean (/services/debugsoap?wsdl). Clearly this should not be in the final (production) version. Once we establish a permanent database (Postgres?) and deployment, this can be removed completely.

Fixed in 7c743fd03161ba0b26a4a34ddd993953881c6eb2
