### ISSUE TITLE
Failing XmlImporterTest

### ISSUE THREAD

**Issue by mschvarc** [mschvarc/PB138-Inventory-Management#20]
XmlImporterTest#testItems fails on NotImplementedException
I've added Travis-CI checks now, so please do not commit failing tests to the master branch. 

Additionally, if time permits please make your test more robust, for example:
You import the XML and verify no exception was thrown (this is OK)
However, you do not check if any item was actually imported into the database. You could do even a simple check: number of items before import, number of items after import increased. You could use service/repository/facade depending on what level of abstraction you think is correct. This check is then not strictly dependent on the example import XML (if it should change in the future).

**Comment by HonzaCech** [comment]
I'm aware of the test failing on NotImplementedException, it's because the importer is not really implemented(so far it only throws exception if xml is not valid), and neither is the test, and this is the reminder for me
