### ISSUE TITLE
Ean regex

### ISSUE THREAD

**Issue by HonzaCech** [mschvarc/PB138-Inventory-Management#22]
i have a feeling that your regex will let some string like aaa0000000000001bbbb (letters, 13 numbers, letters) pass as well, maybe you could put a restriction on length as well (so the length will have to be 13)

**Comment by elederovam** [comment]
With "aaa0000000000001bbbb" string in ean the validation fails, so it should be all right, isn't it?
But thanks, I've just noticed that I haven't updated the resources in tests.

**Comment by HonzaCech** [comment]
i haven't really tried it in the validation, just in some regex checker, because just "d{13}" doesn't say anything about what is before or after that, but maybe the regexes in xml schema work differently, OK then.

**Comment by mschvarc** [comment]
Related to https://github.com/mschvarc/PB138-Inventory-Management/issues/8 and the parent issue https://github.com/mschvarc/PB138-Inventory-Management/issues/7

\d{13} should be fine, XML regexes implicitly add ^regex_here$

"XML schema always implicitly anchors the entire regular expression. The regex must match the whole element for the element to be considered valid. If you have the pattern regexp, the XML schema validator will apply it in the same way as say Perl, Java or .NET would do with the pattern ^regexp$"
Source: http://www.regular-expressions.info/xml.html

**Comment by HonzaCech** [comment]
Ok, didn't know that, thanks!
