### ISSUE TITLE
ItemExporter produces invalid XML from Web download

### ISSUE THREAD

**Issue by mschvarc** [mschvarc/PB138-Inventory-Management#27]
Attempting to export and download XML from Web results in an invalid XML being generated. The exported(downloaded) file contains NUL Unicode characters. Possible encoding issue.

**Comment by HonzaCech** [comment]
String exported by my exporter is
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<items/>
```
including newlines, I guess this is alright, isn't it?

**Comment by mschvarc** [comment]
Thank you, it appears that the issue is either in SOAP String serialization or in the web layer.
Newlines are replaced by U+0000
Edit: SOAP exportAllItemsToXml() returns correctly encoded/escaped inner XML, so the issue is in the Web layer with processing.

**Comment by dee-gmiterko** [comment]
I'm unable to reproduce this bug.. there are no NUL characters or newlines for me. Which browser/paltform did you use?

**Comment by mschvarc** [comment]
Hi, still able to reproduce on SNAPSHOT build. 
Chrome 58 x64 / Windows 8.1 && Firefox 52

Steps to reproduce:
1. Add test data
2. http://localhost:8080/#/import-export Click Export
3. Inspect resulting file in Notepad++

**Comment by dee-gmiterko** [comment]
Somehow resolved..
