### ISSUE TITLE
Creates facades for creating and updating objects

### ISSUE THREAD

**Issue by HonzaCech** [mschvarc/PB138-Inventory-Management#3]

**Comment by HonzaCech** [comment]
ItemFacade - 
Item updateItemFromWeb(int ean, int newAmount, int newThreshold, string newUnit)
Collection<Item> getAllItems()
Collection<Item> getAllItemsByCategory(String categoryName)
CategoryFacade - 
Collection<Category> getAllCategories()

**Comment by HonzaCech** [comment]
Done

**Comment by mschvarc** [comment]
Implemented in https://github.com/mschvarc/PB138-Inventory-Management/pull/12
