### ISSUE TITLE
Inconsistency in wiki

### ISSUE THREAD

**Issue by HonzaCech** [mschvarc/PB138-Inventory-Management#5]
In DevEnv wiki page, the text says to write target\generated-sources\annotations in Test source, but in picture, there is target\generated-sources\test-annotations in Test source. Which one is right?

**Comment by mschvarc** [comment]
Thank you Honza, I've updated the wiki.
[Fixed in latest wiki version](https://github.com/mschvarc/PB138-Inventory-Management/wiki/DevEnv-Setup/31a566b8bf505b5c762bf89d5a0e23e67de1a9ff)
