### ISSUE TITLE
Create XML Schemas

### ISSUE THREAD

**Issue by mschvarc** [mschvarc/PB138-Inventory-Management#6]
Decide on XML schemas for the following files:

- Import of Sales, Shipments
- Export of all Items in DB
- Overview export of Sales for {day/week/month}
- And any others that may be required.

[Preliminary version](https://github.com/mschvarc/PB138-Inventory-Management/wiki/XML-Data-format)

**Comment by mschvarc** [comment]
Preliminary work in 9076ce743e8f6a24006114b29147d53249d35c6f
Task not done yet, see https://github.com/mschvarc/PB138-Inventory-Management/issues/8

**Comment by HonzaCech** [comment]
Could you create schemas for exporter? (you can see how the export looks in xml eporter tests, or I will maybe write it to wiki)

**Comment by mschvarc** [comment]
Item Export schema implemented in e70a2454d35184b0eb310bed32cfed5410b4813b
Only missing schema is now Overview Export

**Comment by mschvarc** [comment]
OverviewExport schema implemented in 30c36179007c8464560341f4a62acc8a58fa4c6d
Task completed
