### ISSUE TITLE
Create new Item + Category XML importer

### ISSUE THREAD

**Issue by mschvarc** [mschvarc/PB138-Inventory-Management#7]
User must be able to import newly created Items and Categories
Sales+Shipment importer should not handle updating category/item names

**Comment by mschvarc** [comment]
Missing Item export schema, see comments on https://github.com/mschvarc/PB138-Inventory-Management/pull/23
All input and output XML files should be validated against a schema.

What is the status of this issue besides the missing schema? pb138.service.XmlImportExport.* seems to be finished.

**Comment by HonzaCech** [comment]
I think that this is all done and I just forgot to close this issue.
Implemented in 6077028
